### ISSUE TITLE
Утилита проверки ссылочной целостности

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-utils#1]
Та, что работает в wb при старте приложения

**Comment by unpete** [comment]
При статре приложения проверяется лишь существование объекта номенклатуры при наличии ссылки в индексе цен.
Желательно проверить не только номенклатуру, но и другие справочники.
Искать оборванность внутри продукций заказов не обязательно - это потребовало бы много машинного времени и трафика, но ссылки внутри вставок, фурнитур, соединений и т.д., надо проверять.

**Comment by nmivan** [comment]
@unpete, как думаешь, актуальна эта задача именно в utils?

**Comment by nmivan** [comment]
Возьму на себя смелость закрыть эту задачу, т.к. инструменты проверки ссылочной целостности появились в Консилиуме.
